In [ ]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

In [ ]:
start -- 

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.models import load_model
from sklearn.model_selection import train_test_split
from keras import optimizers
import pandas as pd
import numpy as np

In [6]:
import os
datapath = os.listdir("./static/data/")
datapath = [i for i in datapath if 'A' in i]
print(datapath)

['A000100_유한양행.csv', 'A000640_동아쏘시오홀딩스.csv', 'A001630_종근당.csv', 'A006280_녹십자.csv', 'A008930_한미사이언스.csv', 'A009290_광동제약.csv', 'A069620_대웅제약.csv', 'A096760_JW홀딩스.csv', 'A128940_한미약품.csv', 'A249420_일동제약.csv']


In [ ]:
for i in range(len(datapath)):
    df = pd.read_csv('./static/data/%s' % datapath[i], engine='python',encoding='CP949',index_col=0,error_bad_lines=False)
    df = df.reset_index(drop=True)
    
    # data drop
    df = df.drop("일자",axis=1)
    df = df.drop("시간",axis=1)

    # label
    df2 = df["현재가"]
    df2 = df2.to_frame()
    df2 = df2.drop([0])
    df2.rename(columns={"현재가":"미래가"},inplace=True)
    df2 = df2.reset_index(drop = True)
    
    df_merge = pd.merge(df, df2, how="outer", left_index=True, right_index=True)
    dataset = df_merge.values

    X = data_set[:, 0:2]
    Y = data_set[:, 2:3]

    X_train, X_validation, Y_train, Y_validation = train_test_split(X, Y,test_size=0.3)

    model = Sequential()
    model.add(Dense(8, input_dim=2, activation='relu'))
    model.add(Dense(12, activation='relu'))
    model.add(Dense(8, activation='relu'))
    model.
    modkeras.layers.Dropout(rate, noise_shape=None, seed=None)
    model.add(Dense(4))
    model.add(Dense(1))

    adam = optimizers.Adam(lr=0.001)
    model.compile(loss='mean_squared_error', optimizer=adam, metrics=['accuracy','mean_squared_error'])

    model.fit(X_train, Y_train, epochs=100, batch_size=40)

    Y_prediction = model.predict(X_validation).flatten()

    model.save('dnn_sample_model.h5')
    for i in range(10):
        real_price = Y_validation[i]
        predicted_price = Y_prediction[i]
        print('Real Price: {}, Predicted Price: {}'.format(str(real_price),str(predicted_price)))
    

In [3]:


df = pd.read_csv('./data/A000100_유한양행.csv', engine='python',encoding='CP949',index_col=0,error_bad_lines=False)
df.head()
df = df.reset_index(drop=True)

In [33]:
df = df[df.일자 < 20180103]
df = df[df.시간 < 1501]
df.head()

일자    시간     현재가  거래량
0  20180102  1001  219000  206
1  20180102  1002  219000   68
2  20180102  1003  220000  407
3  20180102  1004  219000  317
4  20180102  1005  217500   88

In [4]:
df = df.drop("일자",axis=1)
df = df.drop("시간",axis=1)


In [5]:
print(len(df))

df.head()
df2 = df["현재가"]
print(len(df2))

print(type(df2))
df2 = df2.to_frame()

df2 = df2.drop([0])

print(len(df2))
df2.rename(columns={"현재가":"미래가"},inplace=True)
df2.head()

df2 = df2.reset_index(drop = True)
df2.head()
print(len(df2))
print(df2)

df.head()

a = pd.merge(df, df2, how="outer", left_index=True, right_index=True)
a.head()

data_set = a.values

74200
74200
<class 'pandas.core.series.Series'>
74199
74199
          미래가
0      219000
1      220000
2      219000
3      217500
4      217500
5      217000
6      217000
7      217000
8      216500
9      215500
10     215500
11     215000
12     215500
13     217000
14     217000
15     217000
16     216500
17     216500
18     216500
19     216500
20     217000
21     216500
22     216000
23     216500
24     216000
25     216000
26     216000
27     216500
28     216000
29     216000
...       ...
74169  206500
74170  206500
74171  206000
74172  207500
74173  207000
74174  206500
74175  206500
74176  206500
74177  206500
74178  206500
74179  206000
74180  206000
74181  206500
74182  206500
74183  206500
74184  206000
74185  206500
74186  206500
74187  206500
74188  206000
74189  206000
74190  206500
74191  206500
74192  206500
74193  206500
74194  206500
74195  206500
74196  206000
74197  206500
74198  206500

[74199 rows x 1 columns]


In [6]:
print(len(data_set))
print(data_set)

74200
[[2.190e+05 2.060e+02 2.190e+05]
 [2.190e+05 6.800e+01 2.200e+05]
 [2.200e+05 4.070e+02 2.190e+05]
 ...
 [2.060e+05 5.230e+02 2.065e+05]
 [2.065e+05 4.800e+01 2.065e+05]
 [2.065e+05 2.740e+03       nan]]


In [7]:
def json_save(datapath,result):
    with open("%s%s.json" % (datapath,"todayStock") , "w", encoding="utf-8") as file:
        json.dump(result, file ,ensure_ascii=False, indent="\t")            
    return None

In [10]:
X = data_set[:, 0:2]
Y = data_set[:, 2:3]

X_train, X_validation, Y_train, Y_validation = train_test_split(X, Y,test_size=0.3)

model = Sequential()
model.add(Dense(8, input_dim=2, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(4))
model.add(Dense(1))

adam = optimizers.Adam(lr=0.001)
model.compile(loss='mean_squared_error', optimizer=adam, metrics=['accuracy','mean_squared_error'])

model.fit(X_train, Y_train, epochs=100, batch_size=40)

Y_prediction = model.predict(X_validation).flatten()

model.save('dnn_sample_model.h5')
for i in range(10):
    real_price = Y_validation[i]
    predicted_price = Y_prediction[i]
    print('Real Price: {}, Predicted Price: {}'.format(str(real_price),str(predicted_price)))

Epoch 1/100
51940/51940 [==============================] - 7s 143us/step - loss: 4633905941.0854 - acc: 4.6207e-04 - mean_squared_error: 4633905941.0854
Epoch 2/100
51940/51940 [==============================] - 7s 142us/step - loss: 600352.7496 - acc: 5.9684e-04 - mean_squared_error: 600352.7496
Epoch 3/100
51940/51940 [==============================] - 7s 142us/step - loss: 366129.9202 - acc: 0.0012 - mean_squared_error: 366129.9202
Epoch 4/100
51940/51940 [==============================] - 8s 157us/step - loss: 233782.2723 - acc: 0.0023 - mean_squared_error: 233782.2723
Epoch 5/100
51940/51940 [==============================] - 9s 166us/step - loss: 181503.8890 - acc: 0.0029 - mean_squared_error: 181503.8890
Epoch 6/100
51940/51940 [==============================] - 8s 155us/step - loss: 171643.1487 - acc: 0.0018 - mean_squared_error: 171643.1487
Epoch 7/100
51940/51940 [==============================] - 8s 156us/step - loss: 181088.6570 - acc: 0.0014 - mean_squared_error: 181088.65

51940/51940 [==============================] - 7s 127us/step - loss: 193420.5303 - acc: 9.0489e-04 - mean_squared_error: 193420.5303
Epoch 59/100
51940/51940 [==============================] - 7s 126us/step - loss: 198595.0688 - acc: 6.3535e-04 - mean_squared_error: 198595.0688
Epoch 60/100
51940/51940 [==============================] - 7s 126us/step - loss: 205591.4758 - acc: 0.0011 - mean_squared_error: 205591.4758
Epoch 61/100
51940/51940 [==============================] - 7s 125us/step - loss: 187441.5659 - acc: 0.0013 - mean_squared_error: 187441.5659
Epoch 62/100
51940/51940 [==============================] - 7s 126us/step - loss: 203843.5126 - acc: 8.0863e-04 - mean_squared_error: 203843.5126
Epoch 63/100
51940/51940 [==============================] - 7s 127us/step - loss: 191476.7209 - acc: 0.0011 - mean_squared_error: 191476.7209
Epoch 64/100
51940/51940 [==============================] - 7s 129us/step - loss: 198260.8809 - acc: 0.0012 - mean_squared_error: 198260.8809
Epoch 6

In [1]:
import os
import json
import numpy as np
from keras.models import load_model
def loadToModel():
    jsondata = os.listdir("./static/data/")
    jsondata = [i for i in jsondata if 'json'in i]
    isRead = True
    while isRead:
        try:
            with open('./static/data/%s' % "".join(jsondata), encoding='UTF8') as today_file:
                jsondata = json.load(today_file)
            isRead = False
        except IOError:
            print("retry...")
    stock_list = list(jsondata.keys())
    learning_result = {}
    for i in stock_list:
        learning_result[str(i)] = [{"DNN_PRICE" : []}]
    
    #print(learning_result)
    for 
    arr = np.array([[int(jsondata[stock_list[0]][1]["STOCK_PRICE"][-2]),int(jsondata[stock_list[0]][2]["STOCK_VOLUME"][-2])]])
    model = load_model('./learning/dnn_sample_model.h5')
    y = int(jsondata[stock_list[0]][1]["STOCK_PRICE"][-1])
    predict_price = model.predict(arr).flatten()
    
    
          


C:\python\Anaconda3\envs\deeplearning\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
loadToModel()

[[178000  90410]]
178000
[180430.33]


In [38]:

print(arr)
print(X_validation)
print(type(X_validation))

[177000  54134]
[[2.365e+05 6.000e+00]
 [2.265e+05 1.720e+02]
 [2.070e+05 9.000e+01]
 ...
 [2.090e+05 2.470e+02]
 [2.145e+05 2.270e+02]
 [2.225e+05 2.200e+02]]
<class 'numpy.ndarray'>


In [ ]:
xhat = x_test[xhat_idx]

# 3. 모델 사용하기
yhat = model.predict_classes(xhat)

for i in range(5):
    print('True : ' + str(argmax(y_test[xhat_idx[i]])) + ', Predict : ' + str(yhat[i]))

In [ ]:
from keras.backend import tensorflow_backend as K
import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
K.set_session(tf.Session(config=config))


model = load_model('dnn_sample_model.h5')
arr = np.array([[177000,54134]])
y = model.predict(arr).flatten()
y_r  = 177000

print(y)

In [91]:
load_model()

RecursionError: maximum recursion depth exceeded while decoding a JSON array from a unicode string

In [34]:
a = ["11"]
a[-1]

'11'

In [ ]:
          
    
    
    if not datadir:
            datadir = {}
            for i in range(10):
                datadir["%s_%s" % (self.code[i],self.stock[i])] = []
                datadir["%s_%s" % (self.code[i],self.stock[i])].append({"STOCK_DATE":[]})
                datadir["%s_%s" % (self.code[i],self.stock[i])].append({"STOCK_PRICE":[]})
                datadir["%s_%s" % (self.code[i],self.stock[i])].append({"STOCK_VOLUME":[]})    
        else:
             with open('../data/%s' % "".join(self.result)) as data_file:    
                self.result = json.load(data_file)

In [26]:
load_model()

['todayStock.json']


In [12]:
load_model()

['todayStock.json']


In [25]:
a = 10
b = -1
isRead = True
while isRead:
    try:
        b = b + 1
        print(a/b)  
        isRead=False
    except ZeroDivisionError:
        print("dd")
    
          
          


dd
10.0
