In [41]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from keras import optimizers
import pandas as pd
import numpy as np
from keras.models import load_model



In [42]:
df = pd.read_csv('../data/A000100_유한양행.csv', engine='python',encoding='CP949',index_col=0,error_bad_lines=False)
df.head()
df = df.reset_index(drop=True)

In [33]:
df = df[df.일자 < 20180103]
df = df[df.시간 < 1501]
df.head()

일자    시간     현재가  거래량
0  20180102  1001  219000  206
1  20180102  1002  219000   68
2  20180102  1003  220000  407
3  20180102  1004  219000  317
4  20180102  1005  217500   88

In [43]:
df = df.drop("일자",axis=1)
df = df.drop("시간",axis=1)


In [44]:
print(len(df))

df.head()
df2 = df["현재가"]
print(len(df2))

print(type(df2))
df2 = df2.to_frame()

df2 = df2.drop([0])

print(len(df2))
df2.rename(columns={"현재가":"미래가"},inplace=True)
df2.head()

df2 = df2.reset_index(drop = True)
df2.head()
print(len(df2))
print(df2)

df.head()

a = pd.merge(df, df2, how="outer", left_index=True, right_index=True)
a.head()

data_set = a.values

74200
74200
<class 'pandas.core.series.Series'>
74199
74199
          미래가
0      219000
1      220000
2      219000
3      217500
4      217500
5      217000
6      217000
7      217000
8      216500
9      215500
10     215500
11     215000
12     215500
13     217000
14     217000
15     217000
16     216500
17     216500
18     216500
19     216500
20     217000
21     216500
22     216000
23     216500
24     216000
25     216000
26     216000
27     216500
28     216000
29     216000
...       ...
74169  206500
74170  206500
74171  206000
74172  207500
74173  207000
74174  206500
74175  206500
74176  206500
74177  206500
74178  206500
74179  206000
74180  206000
74181  206500
74182  206500
74183  206500
74184  206000
74185  206500
74186  206500
74187  206500
74188  206000
74189  206000
74190  206500
74191  206500
74192  206500
74193  206500
74194  206500
74195  206500
74196  206000
74197  206500
74198  206500

[74199 rows x 1 columns]


In [45]:
print(len(data_set))
print(data_set)

74200
[[2.190e+05 2.060e+02 2.190e+05]
 [2.190e+05 6.800e+01 2.200e+05]
 [2.200e+05 4.070e+02 2.190e+05]
 ...
 [2.060e+05 5.230e+02 2.065e+05]
 [2.065e+05 4.800e+01 2.065e+05]
 [2.065e+05 2.740e+03       nan]]


In [46]:
a.tail()



현재가   거래량       미래가
74195  206500    83  206500.0
74196  206500   103  206000.0
74197  206000   523  206500.0
74198  206500    48  206500.0
74199  206500  2740       NaN

In [48]:
X = data_set[:, 0:2]
Y = data_set[:, 2:3]

X_train, X_validation, Y_train, Y_validation = train_test_split(X, Y,test_size=0.3)

model = Sequential()
model.add(Dense(8, input_dim=2, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(4))
model.add(Dense(1))

adam = optimizers.Adam(lr=0.001)
model.compile(loss='mean_squared_error', optimizer=adam, metrics=['accuracy','mean_squared_error'])

model.fit(X_train, Y_train, epochs=100, batch_size=40)

Y_prediction = model.predict(X_validation).flatten()

model.save('dnn_sample_model.h5')
for i in range(10):
    real_price = Y_validation[i]
    predicted_price = Y_prediction[i]
    print('Real Price: {}, Predicted Price: {}'.format(str(real_price),str(predicted_price)))

Epoch 1/100
51940/51940 [==============================] - 9s 166us/step - loss: 483380495.0292 - acc: 0.0055 - mean_squared_error: 483380495.0292
Epoch 2/100
51940/51940 [==============================] - 9s 169us/step - loss: 162842.2135 - acc: 0.0057 - mean_squared_error: 162842.2135
Epoch 3/100
51940/51940 [==============================] - 9s 177us/step - loss: 163573.6957 - acc: 0.0051 - mean_squared_error: 163573.6957
Epoch 4/100
51940/51940 [==============================] - 9s 175us/step - loss: 165345.7295 - acc: 0.0039 - mean_squared_error: 165345.7295
Epoch 5/100
51940/51940 [==============================] - 9s 173us/step - loss: 169851.8296 - acc: 0.0019 - mean_squared_error: 169851.8296
Epoch 6/100
51940/51940 [==============================] - 9s 167us/step - loss: 182155.9966 - acc: 0.0012 - mean_squared_error: 182155.9966
Epoch 7/100
51940/51940 [==============================] - 8s 162us/step - loss: 204409.8010 - acc: 8.2788e-04 - mean_squared_error: 204409.8010
Epo

51940/51940 [==============================] - 7s 140us/step - loss: 206559.1328 - acc: 6.7385e-04 - mean_squared_error: 206559.1328
Epoch 58/100
51940/51940 [==============================] - 8s 146us/step - loss: 207190.8834 - acc: 0.0010 - mean_squared_error: 207190.8834
Epoch 59/100
51940/51940 [==============================] - 7s 139us/step - loss: 203192.2390 - acc: 4.8132e-04 - mean_squared_error: 203192.2390
Epoch 60/100
51940/51940 [==============================] - 7s 139us/step - loss: 201375.1203 - acc: 5.1983e-04 - mean_squared_error: 201375.1203
Epoch 61/100
51940/51940 [==============================] - 7s 141us/step - loss: 202625.1149 - acc: 7.7012e-04 - mean_squared_error: 202625.1149
Epoch 62/100
51940/51940 [==============================] - 7s 139us/step - loss: 211584.5177 - acc: 0.0014 - mean_squared_error: 211584.5177
Epoch 63/100
51940/51940 [==============================] - 7s 139us/step - loss: 206493.3834 - acc: 0.0015 - mean_squared_error: 206493.3834
Epo

In [49]:
from keras.models import load_model
model = load_model('dnn_sample_model.h5')
arr = np.array([[177000,54134]])
y = model.predict(arr).flatten()
y_r  = 177000




print(y)

[167483.2]


In [38]:

print(arr)
print(X_validation)
print(type(X_validation))

[177000  54134]
[[2.365e+05 6.000e+00]
 [2.265e+05 1.720e+02]
 [2.070e+05 9.000e+01]
 ...
 [2.090e+05 2.470e+02]
 [2.145e+05 2.270e+02]
 [2.225e+05 2.200e+02]]
<class 'numpy.ndarray'>


In [ ]:
xhat = x_test[xhat_idx]

# 3. 모델 사용하기
yhat = model.predict_classes(xhat)

for i in range(5):
    print('True : ' + str(argmax(y_test[xhat_idx[i]])) + ', Predict : ' + str(yhat[i]))